root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jsdoc/recommended
  - eslint-config-prettier
plugins:
  - jsdoc
  - tsdoc
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  createDefaultProgram: true
  project: ./tsconfig.json
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: warn
  require-jsdoc: warn
  valid-jsdoc: off
  import/no-named-as-default: off
  jsdoc/require-param-type: off
  jsdoc/require-param: ['off', { enableRootFixer: false }]
  jsdoc/require-returns-description: off
  jsdoc/require-returns-type: off
  jsdoc/require-returns: off
  tsdoc/syntax: warn
settings:
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
